apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: l3pk9h0vb-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: l3pk9h0vb-python 
  name: l3pk9h0vb-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: l3pk9h0vb-python
    weight: 100 
